name: build

on:
  push:
    branches: [master]

jobs:
  esp-elf-gcc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
      - name: Install ESP-IDF
        run: |
          mkdir -p ~/esp
          cd ~/esp
          git clone --recursive https://github.com/espressif/esp-idf.git
          cd ~/esp/esp-idf
          ./install.sh esp32s3
      - run: |
          . $HOME/esp/esp-idf/export.sh
          cd $GITHUB_WORKSPACE
          cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=$IDF_PATH/tools/cmake/toolchain-esp32s3.cmake -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DIDF_TARGET=esp32s3 -DCCACHE_ENABLE=0
          idf.py build
